name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: My_ENV

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm ci

      - name: Rodar push Prisma
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
        run: npx prisma db push
      
      - name: Baseline database 
        run: npx prisma migrate resolve --applied 20260704231106_require_comments_content

      - name: Gerar o Prisma
        run: npx prisma generate

      - name: Rodar testes
        run: npm test
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          JWT_SECRET: ${{vars.JWT_SECRET}}

      - name: Build do projeto
        run: npm run build